export const SET_USER = 'SET_USER'
export const SET_USER_ERROR = 'SET_USER_ERROR'
export const USER_LOGOUT = 'USER_LOGOUT'

export const SET_CONTACTS = 'SET_CONTACTS'
export const SET_CONTACTS_ERROR = 'SET_CONTACTS_ERROR'
export const ADD_CONTACT = 'ADD_CONTACT'
export const ADD_CONTACT_ERROR = 'ADD_CONTACT_ERROR'

export const DELETE_CONTACT = 'DELETE_CONTACT'
export const DELETE_CONTACT_ERROR = 'DELETE_CONTACT_ERROR'

export const EDIT_CONTACT = 'EDIT_CONTACT'
export const EDIT_CONTACT_ERROR = 'EDIT_CONTACT_ERROR'
